#!/usr/bin/env bash
# scratch_boot.sh — run `troubled` as a SCRATCH daemon that cannot outlive the
# thing that booted it (TRBL-042).
#
# The failure class: a per-tick scratch boot (scratch HOME + scratch state
# root, documented ports 7643/7644) outlived its tick, the next tick's first
# `go test ./internal/lifecycle/` red-ed on TestPreflightBindsHappy with a bare
# `bind: address already in use`, and the repo's own verification contradicted
# the docs ("7643/7644 must be free"). This wrapper closes that hole from the
# booting side:
#
#   * it refuses to start when the configured binds are already held (the
#     diagnostics name the holder; see internal/lifecycle PreflightBinds);
#   * it REPLACES ITSELF with the daemon via exec, so there is no wrapper
#     process to orphan: killing the shell pid kills the daemon, and the
#     daemon can never outlive the terminal/pipeline that started it;
#   * `--report` prints the binds a given scratch config will hold as
#     SCRATCH_PORTS=, so a tick can record what it started and the next one
#     can prove what to kill.
#
# Usage:
#   tests/e2e/scratch_boot.sh [path-to-troubled] [config-file]
#       SCRATCH_HOME (default: ~/.local/state/trouble-scratch-home-<pid>)
#         is created as the scratch HOME; the state root and every secret
#         file live under it. SCRATCH_INGEST_PORT / SCRATCH_DASH_PORT
#         override the ports in the generated config (default: the
#         documented 7643 / 7644).
#   tests/e2e/scratch_boot.sh --report <config-file>
#
# Every scratch boot MUST go through this wrapper (or document why it can
# not): a bare background `troubled` in a tick is the bug this file exists to
# prevent. The normal (non-scratch) boot path is untouched — this script is
# a testing-hygiene convention, not runtime code.
set -uo pipefail

fail() { printf 'scratch_boot: %s\n' "$*" >&2; exit 1; }

usage() {
	printf 'usage: scratch_boot.sh [path-to-troubled] [config-file]\n       scratch_boot.sh --report <config-file>\n' >&2
	exit 2
}

# grep_toml_scalar KEY FILE — the last scalar assignment of KEY in FILE.
grep_toml_scalar() {
	grep -E "^[[:space:]]*$1[[:space:]]*=" "$2" | tail -1 |
		sed -E 's/^[[:space:]]*[^=]+=[[:space:]]*"?([^"#]*)"?.*/\1/' | tr -d '[:space:]'
}

# port_holders PORT — pids with a LISTEN socket on :PORT (ss parses /proc).
port_holders() { ss -tlnp 2>/dev/null | grep -E ":$1[[:space:]]" | grep -oE 'pid=[0-9]+' | cut -d= -f2 | sort -u; }

# guard_binds BIND... — refuse to run when any bind is already held.
guard_binds() {
	local rc=0
	for bind in "$@"; do
		local port="${bind##*:}"
		local pids
		pids=$(port_holders "$port")
		if [[ -n "$pids" ]]; then
			printf 'scratch_boot: TROUBLE-SCRATCH-DAEMON: %s is already held — pids: %s\n' \
				"$bind" "$(echo "$pids" | tr '\n' ' ')" >&2
			ps -o pid,lstart,cmd -p "$(echo "$pids" | tr '\n' ',' | sed 's/,$//')" >&2 2>/dev/null
			rc=3
		fi
	done
	return "$rc"
}

report() {
	[[ -f "$1" ]] || fail "config not found: $1"
	local ingest dash
	ingest=$(grep_toml_scalar 'bind' <(sed -n '/^\[ingest\]/,/^\[/p' "$1"))
	dash=$(grep_toml_scalar 'bind' <(sed -n '/^\[dashboard\]/,/^\[/p' "$1"))
	[[ -n "$ingest" && -n "$dash" ]] || fail "no ingest/dashboard bind in $1"
	printf 'SCRATCH_PORTS=%s\n' "$ingest $dash"
}

[[ "${1:-}" == "--report" ]] && { [[ $# -eq 2 ]] || usage; report "$2"; exit 0; }
[[ $# -le 2 ]] || usage

BIN="${1:-./bin/troubled}"
[[ -x "$BIN" ]] || fail "missing binary $BIN (run: go build -o bin/troubled ./cmd/troubled)"

SCRATCH_HOME="${SCRATCH_HOME:-$HOME/.local/state/trouble-scratch-home-$$}"
CFG="${2:-$SCRATCH_HOME/.config/trouble/config.toml}"

if [[ ! -f "$CFG" ]]; then
	[[ "$CFG" == "$SCRATCH_HOME/"* ]] || fail "refusing to generate a config outside the scratch HOME: $CFG"
	INGEST="${SCRATCH_INGEST_PORT:-7643}"
	DASH="${SCRATCH_DASH_PORT:-7644}"
	mkdir -p "$SCRATCH_HOME/.config/trouble" "$SCRATCH_HOME/state" || fail "cannot create $SCRATCH_HOME"
	chmod 700 "$SCRATCH_HOME" "$SCRATCH_HOME/state"
	: > "$SCRATCH_HOME/.config/trouble/trouble.env"
	chmod 600 "$SCRATCH_HOME/.config/trouble/trouble.env"
	cat > "$CFG" <<EOF
# Generated by tests/e2e/scratch_boot.sh — a scratch boot (TRBL-042).
# Scratch HOME + scratch state root; NEVER point these at a real state root.
state_root = "$SCRATCH_HOME/state"
config_path = "$CFG"

[secrets]
environment_file = "$SCRATCH_HOME/.config/trouble/trouble.env"

[checker]
interval = "60s"
confirm_runs = 2
alarm_command = []

[ingest]
bind = "127.0.0.1:$INGEST"
advertised_host = "trouble-scratch.example.net"

[ingest.auth]
loopback_dsn = true
nonloopback_mode = "token"
public_require_proxy = true

[dashboard]
bind = "127.0.0.1:$DASH"

[dashboard.auth]
transport = "cookie"
identity_provider = ""
session_ttl = "24h"

[hub]
mode = "hub"
url = ""
forward_project_id = ""
token = ""
protocol_version = 1
forward_batch_records = 200
forward_batch_bytes = 524288
retry_base = "2s"
retry_max = "5m"
dedup_lru = 65536

[spool]
budget_bytes = 268435456
gap_reserve_bytes = 2097152
fsync = "group"
fsync_window_ms = 200

[verify]
zone_windows = "loopback=10m lan=15m tailnet=20m public=30m"

[escalate]
channels = []
timeout = "10s"

[origin]
host_id = ""
hub_id = ""

[issues]
enabled = false

[skills]
enabled = false

[[projects]]
id = "1"
slug = "trouble-scratch"
public_key = "0123456789abcdef0123456789abcdef"
quota_epm = 600
enabled = true
EOF
	chmod 600 "$CFG"
fi

INGEST_BIND=$(grep_toml_scalar 'bind' <(sed -n '/^\[ingest\]/,/^\[/p' "$CFG"))
DASH_BIND=$(grep_toml_scalar 'bind' <(sed -n '/^\[dashboard\]/,/^\[/p' "$CFG"))
[[ -n "$INGEST_BIND" && -n "$DASH_BIND" ]] || fail "no ingest/dashboard bind in $CFG"

guard_binds "$INGEST_BIND" "$DASH_BIND" || fail "documented bind already held — kill the holder above by exact PID; do NOT boot a second daemon"

printf 'scratch_boot: HOME=%s cfg=%s ports=%s %s\n' \
	"$SCRATCH_HOME" "$CFG" "$INGEST_BIND,$DASH_BIND" "report: $(basename "$0") --report $CFG" >&2
exec env HOME="$SCRATCH_HOME" "$BIN" --config "$CFG"
